version: "3"

services:
  jhub:
    image: jupyterhub:latest
    container_name: jupyterhub_r3b
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - jupyterhub
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./templates:/usr/local/share/jupyter/hub/templates"
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py"
networks:
  jupyterhub:
    name: jupyterhub
